# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  schedule:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    # * is a special character in YAML so you have to quote this string
    #- cron:  '1 0-23 * * *'
    - cron: '5 */12 * * *'   # Runs at 5 minutes past the hour, every 12 hours.
  workflow_dispatch:
  #pull_request:
    #branches: [ "main" ]
  #push:
    #branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK version
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
      #uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Run Java Application
      run: java -jar target/bing-wallpaper-jar-with-dependencies.jar
    - name: Write update time
      run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         [ -z "$(git diff)" ] || echo "updated in [$(date '+%Y-%m-%d %H:%M:%S')]." >> update.log
    - name: Commit files
      run: |
         git config --local user.name 'github-actions'
         git config --local user.email 'noreply@github.com'
         git pull
         git add update.log
         git add README.md
         git add bing-wallpaper.md
         git add picture/*
         git add docs/*
         git add zh-cn/*
         git commit -m "$(date '+%m-%d %H:%M'), updated" || { echo 'No update'; exit 0; }
         git push
